//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTheater1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BINHLUAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BINHLUAN()
        {
            this.PHIMs = new HashSet<PHIM>();
        }
    
        public string MABINHLUAN { get; set; }
        public string MATHANHVIEN { get; set; }
        public string MAPHIM { get; set; }
        public string NOIDUNG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIM> PHIMs { get; set; }
    }
}
