//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTheater1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GHE
    {
        public string MAGHE { get; set; }
        public string MATINHTRANGGHE { get; set; }
        public string MAPHONG { get; set; }
        public string MALOAIGHE { get; set; }
    
        public virtual TINHTRANGGHE TINHTRANGGHE { get; set; }
        public virtual PHONG PHONG { get; set; }
        public virtual LOAIGHE LOAIGHE { get; set; }
    }
}
