//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTheater1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GHE
    {
        public string MaPhong { get; set; }
        public string MaRap { get; set; }
        public string Id { get; set; }
        public Nullable<int> IsUsed { get; set; }
    
        public virtual PHONG PHONG { get; set; }
    }
}
