//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTheater1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GHE
    {
        public string Id { get; set; }
        public string MaThongTinChieu { get; set; }
        public string MAVE { get; set; }
        public Nullable<int> IsUsed { get; set; }
        public string MALOAIGHE { get; set; }
    
        public virtual LOAIGHE LOAIGHE { get; set; }
        public virtual THONGTINCHIEU THONGTINCHIEU { get; set; }
        public virtual VE VE { get; set; }
    }
}
