//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTheater1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHONG()
        {
            this.GHEs = new HashSet<GHE>();
            this.THONGTINCHIEUx = new HashSet<THONGTINCHIEU>();
        }
    
        public string MaPhong { get; set; }
        public string MARAP { get; set; }
        public string MaLoaiPhong { get; set; }
        public Nullable<int> SoCho { get; set; }
        public string TenPhong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GHE> GHEs { get; set; }
        public virtual LOAIPHONG LOAIPHONG { get; set; }
        public virtual RAPCHIEUPHIM RAPCHIEUPHIM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THONGTINCHIEU> THONGTINCHIEUx { get; set; }
    }
}
