//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTheater1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANHVIEN
    {
        public string MATV { get; set; }
        public string HOTEN { get; set; }
        public string GIOITINH { get; set; }
        public string SODT { get; set; }
        public string EMAIL { get; set; }
        public string MALOAITV { get; set; }
        public string MAQUOCGIA { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string NGAYSINH { get; set; }
    
        public virtual LOAITHANHVIEN LOAITHANHVIEN { get; set; }
        public virtual QUOCGIA QUOCGIA { get; set; }
    }
}
