//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTheater1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONGTINCHIEU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THONGTINCHIEU()
        {
            this.VEs = new HashSet<VE>();
        }
    
        public string MATHONGTINCHIEU { get; set; }
        public string MAPHIM { get; set; }
        public string THOIGIANCHIEU { get; set; }
        public Nullable<System.DateTime> NGAYCHIEU { get; set; }
        public string MAPHONG { get; set; }
        public string MARAP { get; set; }
    
        public virtual PHIM PHIM { get; set; }
        public virtual PHONG PHONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VE> VEs { get; set; }
    }
}
