//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTheater1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VE()
        {
            this.GHEs = new HashSet<GHE>();
        }
    
        public string MAVE { get; set; }
        public string MATV { get; set; }
        public string MATHONGTINCHIEU { get; set; }
        public string MAVOUCHER { get; set; }
        public Nullable<int> DONGIA { get; set; }
        public string MATINHTRANGVE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GHE> GHEs { get; set; }
        public virtual THONGTINCHIEU THONGTINCHIEU { get; set; }
        public virtual TINHTRANGVE TINHTRANGVE { get; set; }
        public virtual VOUCHER VOUCHER { get; set; }
    }
}
