//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTheater1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOUCHER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VOUCHER()
        {
            this.VEs = new HashSet<VE>();
        }
    
        public string MAVOUCHER { get; set; }
        public string TENVOUCHER { get; set; }
        public string NOIDUNG { get; set; }
        public string NGAYBD { get; set; }
        public string NGAYKT { get; set; }
        public Nullable<int> GIAMGIA { get; set; }
        public string GHICHU { get; set; }
        public string ANHDAIDIEN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VE> VEs { get; set; }
    }
}
