----------------------------------------
--GHE
CREATE TABLE GHE(
	MAGHE			varchar(20) not null,	
	MATINHTRANGGHE	varchar(20),
	MAPHONG			varchar(20),
	MALOAIGHE		varchar(20),
	constraint pk_ghe primary key(MAGHE)
)
GO
-- Khoa ngoai cho bang GHE
ALTER TABLE GHE ADD CONSTRAINT fk01_GHE FOREIGN KEY(MATINHTRANGGHE) REFERENCES TINHTRANGGHE(MATINHTRANGGHE)
GO
ALTER TABLE GHE ADD CONSTRAINT fk02_GHE FOREIGN KEY(MAPHONG) REFERENCES PHONG(MAPHONG)
GO
ALTER TABLE GHE ADD CONSTRAINT fk03_GHE FOREIGN KEY(MALOAIGHE) REFERENCES LOAIGHE(MALOAIGHE)