----------------------------------------
--PHIM
CREATE TABLE PHIM(
	MAPHIM		varchar(20) not null,	
	TENPHIM		varchar(40),
	MAQUOCGIA	varchar(20),
	MALOAIPHIM	varchar(20),
	THOIGIANBD	time,
	THOIGIANKT	time,
	THOILUONG	varchar(20),
	SOLUONGSUAT	smallint,
	ANHDAIDIEN	image,
	MOTA		varchar(200),
	GHICHU		varchar(100),
	MABINHLUAN	varchar(20),
	constraint pk_phim primary key(MAPHIM)
)
GO
-- Khoa ngoai cho bang PHIM
ALTER TABLE PHIM ADD CONSTRAINT fk01_PHIM FOREIGN KEY(MAQUOCGIA)  REFERENCES QUOCGIA(MAQUOCGIA)
GO
ALTER TABLE PHIM ADD CONSTRAINT fk02_PHIM FOREIGN KEY(MALOAIPHIM) REFERENCES LOAIPHIM(MALOAIPHIM)
GO
ALTER TABLE PHIM ADD CONSTRAINT fk03_PHIM FOREIGN KEY(MABINHLUAN) REFERENCES BINHLUAN(MABINHLUAN)