----------------------------------------
--PHONG
CREATE TABLE PHONG(
	MAPHONG				varchar(20) not null,	
	MATINHTRANGPHONG	varchar(20),
	MALOAIPHONG			varchar(20),
	SOCHOCONTRONG		smallint,
	constraint pk_phong primary key(MAPHONG)
)
GO
-- Khoa ngoai cho bang PHONG
ALTER TABLE PHONG ADD CONSTRAINT fk01_PHONG FOREIGN KEY(MATINHTRANGPHONG) REFERENCES TINHTRANGPHONG(MATINHTRANGPHONG)
GO
ALTER TABLE PHONG ADD CONSTRAINT fk02_PHONG FOREIGN KEY(MALOAIPHONG) REFERENCES LOAIPHONG(MALOAIPHONG)