----------------------------------------
--THANHVIEN
CREATE TABLE THANHVIEN(
	MATV		varchar(20) not null,	
	HOTEN		varchar(40),
	GIOITINH	varchar(20),
	SODT		varchar(20),
	EMAIL		varchar(40),
	MALOAITV	varchar(20),
	MAQUOCGIA	varchar(20),	
	constraint pk_tv primary key(MATV)
)
GO
-- Khoa ngoai cho bang THANHVIEN
ALTER TABLE THANHVIEN ADD CONSTRAINT fk01_TV FOREIGN KEY(MALOAITV) REFERENCES LOAITHANHVIEN(MALOAITV)
GO
ALTER TABLE THANHVIEN ADD CONSTRAINT fk02_TV FOREIGN KEY(MAQUOCGIA) REFERENCES QUOCGIA(MAQUOCGIA)